"""
backend/config.py
Generated by @devlead (Step 6: backend-agent) from spec.yaml.
Do not edit manually — re-run '@devlead build' to regenerate.
"""
import os
import json

# ── Azure Identity ────────────────────────────────────────────────────────────
AZURE_CLIENT_ID = os.environ["AZURE_CLIENT_ID"]

# ── AI Foundry ────────────────────────────────────────────────────────────────
# AZURE_AI_PROJECT_ENDPOINT: https://{hub}.services.ai.azure.com/api/projects/{project}/
# Used by: MAF FoundryAgent (agent_framework.foundry) for all agent operations.
# MAF derives the OpenAI inference endpoint internally — no separate AzureOpenAI client needed.
AZURE_AI_PROJECT_ENDPOINT = os.environ["AZURE_AI_PROJECT_ENDPOINT"]

# ── AI Search ─────────────────────────────────────────────────────────────────
AZURE_SEARCH_ENDPOINT = os.environ["AZURE_SEARCH_ENDPOINT"]
AZURE_SEARCH_INDEX = os.environ.get(
    "AZURE_SEARCH_INDEX", "{{SEARCH_INDEX_NAME_PY}}"
)

# ── Storage ───────────────────────────────────────────────────────────────────
AZURE_STORAGE_ACCOUNT = os.environ["AZURE_STORAGE_ACCOUNT_NAME"]

# ── Cosmos DB ────────────────────────────────────────────────────────────────
AZURE_COSMOS_ENDPOINT = os.environ["AZURE_COSMOS_ENDPOINT"]
AZURE_COSMOS_DATABASE = os.environ.get("AZURE_COSMOS_DATABASE", "{{COSMOS_DATABASE_NAME_PY}}")

# ── Branding (spec.yaml Section 2) ───────────────────────────────────────────
CUSTOMER_NAME = os.environ.get("CUSTOMER_NAME", "{{CUSTOMER_NAME_PY}}")
AGENT_NAME = os.environ.get("AGENT_NAME", "{{BRANDING_AGENT_NAME_PY}}")
PRIMARY_COLOR = os.environ.get("PRIMARY_COLOR", "{{BRANDING_PRIMARY_COLOR_PY}}")
ACCENT_COLOR = os.environ.get("ACCENT_COLOR", "{{BRANDING_ACCENT_COLOR_PY}}")
FONT_FAMILY = os.environ.get("FONT_FAMILY", "{{BRANDING_FONT_FAMILY_PY}}")
LOGO_URL = os.environ.get("LOGO_URL", "{{BRANDING_LOGO_URL_PY}}")
WELCOME_MESSAGE = os.environ.get(
    "WELCOME_MESSAGE",
    "{{BRANDING_WELCOME_MESSAGE_PY}}",
)
USE_CASE_TITLE = os.environ.get(
    "USE_CASE_TITLE", "{{BRANDING_USE_CASE_TITLE_PY}}"
)

# ── Frontend behaviour ────────────────────────────────────────────────────────
PROTOTYPE_RESET = os.environ.get("PROTOTYPE_RESET", "true").lower() == "true"

# ── Mock API ──────────────────────────────────────────────────────────────────
MOCK_API_ENABLED = True
MOCK_API_ENDPOINTS_RAW = json.dumps({{MOCK_API_ENDPOINTS_JSON}})

# ── Starter questions (spec.yaml Section 3b) ─────────────────────────────────
STARTER_QUESTIONS = {{STARTER_QUESTIONS_PYTHON}}

# ── Demo scenarios ────────────────────────────────────────────────────────────
# Generated by fill-templates.py — one scenario per agent from manifest.json
SCENARIOS = {{SCENARIOS_PYTHON}}

# ── Agent names (must match agents/ folder names) ─────────────────────────────
AGENT_NAMES = {{AGENT_NAMES_PYTHON}}

